### ISSUE TITLE
Video controls in fullscreen

### ISSUE THREAD

**Issue by onny** [Hipady/Videre#1]
Hey,
is it possible to enable your custom video controls in fullscreen video playback?

Best regards,
Jonas

ps. This html5 video theme is great!

**Comment by rafaelnilton** [comment]
I have the same problem, the custom video controls not working in fullscreen video.

**Comment by Hipady** [comment]
@onny @rafaelnilton Will update this library to a finished product when I have the time. Sorry for the late reply.
